<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Wsla</RootNamespace>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<AssemblyName>Wsla-$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="GenHTTP.Core" Version="9.7.0" />
	  <PackageReference Include="GenHTTP.Modules.Conversion" Version="9.7.0" />
	  <PackageReference Include="GenHTTP.Modules.Functional" Version="9.7.0" />
	  <PackageReference Include="GenHTTP.Modules.Protobuf" Version="9.7.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared-Global\Shared-Global.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../Network-Generator/Network-Generator.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<OutputItemType>Analyzer</OutputItemType>
		</ProjectReference>
	</ItemGroup>

</Project>