<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Wsla.Shared.Global</RootNamespace>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<AssemblyName>Wsla-$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="..\\**\*.meta" />
		<None Remove="..\\**\*.asmdef" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="..\Network-Generator\publish\Wsla-Network-Generator.dll" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MemoryPack" Version="1.21.3" />
	</ItemGroup>
</Project>
