<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Wsla.Shared.Global</RootNamespace>
		<Nullable>disable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Source\Networking\NetworkEntityResource.cs.meta" />
	  <None Remove="Source\Networking\NetworkPrefab.cs.meta" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MemoryPack" Version="1.21.3" />
	</ItemGroup>

</Project>
