<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Wsla.Server.Relay</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>Wsla-$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared-Server\Shared-Server.csproj" />
	</ItemGroup>

</Project>
